---
name: cargo-deny
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  check:
    name: cargo-deny
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v1
